Ria Ann De la Cruz </br>
BS in Computer Science IV

In [2]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


Part 1:
* Create 2 2D arrays, y_hat and y
* Initialize y_hat with 20 linearly spaced numbers between -1 and 1

In [4]:
y_hat = np.linspace(-1, 1, 20) #creating a 1D array name y_hat with 20 numbers between -1 and 1
y_hat

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

* Initialize y with 20 linearly spaced numbers between 0 and 1

In [5]:
y = np.linspace(0, 1, 20) #creating a 1D array name y with 20 numbers between 0 and 1
y

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

* Compute for the shape and dimension of y_hat and y

In [8]:
y_hat.shape #to check for the shape of variable y_hat

(20,)

In [9]:
y_hat.ndim #to check for the number of dimension of the variable y_hat

1

In [10]:
y.shape #to check for the shape of the variable y

(20,)

In [28]:
y.ndim #to check for the number of dimension of variable y

1

Create individual functions for each of the loss functions with y and </br>
y_hat as parameters and each function should return the loss value (L).

Using the given formula where N = the number of observation.

In [100]:
#Getting the value of N
n = len(y_hat)            

Creating a function for the mean squared error L = 1/N [sum of ((y_hat-y)**2)]
* np.sum = overall sum of the array

In [104]:
def MSE(y_hat,y):
    return 1/n*(np.sum((y_hat-y)**2))  
MSE(y_hat, y)

0.3421052631578948

Creating a function for the Mean Absolute Error L = 1/N [sum of (abs(y_hat-y))]
* np.sum = overall sum of the array
* np.abs = getting the absolute value of each element in array

In [105]:
def MAE(y_hat,y):
    return 1/n*(np.sum(np.abs(y_hat-y)))
MAE(y_hat,y)

0.49999999999999994

Creating a function for the Mean Absolute Error L = 1/N [sum of (log(y_hat+1)- log(y+1)**2)]
* np.sum = overall sum of the array
* np.log = getting the logarithmic value of each number in array

In [134]:

def MSLE(y_hat,y):
    #Created an if-else statement to check whether there is a negative number present or not.
    if y_hat[0]>-1 and y[0]>-1:
        result = 1/n*(np.sum((np.log(y_hat+1)- np.log(y+1))**2))
    else:
        result = "There is a negative number in array"
    return(result)
MSLE(y_hat,y)

'There is a negative number in array'

Creating a function for the Mean Absolute Percentage Error
* np.sum = overall sum of the array
* np.abs = getting the absolute value of each number in array

In [140]:
def MAPE(y_hat,y):
    result = 1/n*(np.sum(np.abs((y_hat-y)/y)))
    #Created an if-else statement to check whether the value is undefine or not.
    if result == float(inf) or result == float(-inf):     
        result = "Denominator has a value of zero.It results to undefined number."
    return(result)
MAPE(y_hat,y)

C:\Users\delac\AppData\Local\Temp/ipykernel_15812/1096568994.py:2: RuntimeWarning: divide by zero encountered in true_divide
  result = 1/n*(np.sum(np.abs((y_hat-y)/y)))


'Denominator has a value of zero.It results to undefined number.'

Part 2:</br>
Create a 1d array M {1, 2, …16} using the arange function

In [39]:
M = np.arange(1,17)   #element started from 1 and ends with 17 given that the last number does not included
M

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

* Reshape M into 4x4 array and store it to N

In [84]:
N = M.reshape(4,4)   #reshaping 1D array into a 4x4 array
N

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

* Get the 2nd row of N

In [102]:
N[1,:]  #second row can be found in index 1

array([5, 6, 7, 8])

* Get the minimum values for each column of N

In [103]:
np.min(N, axis= 0)   #min can be found in 0

array([1, 2, 3, 4])

* Get the locations of the minimum values for each column of N

In [91]:
val_index= np.argmin(N, axis = 0)    #getting the index of the min values in column n
"""the np.argmin includes the data type of the elements when printing, hence
using for loop to print the indexes save in variable val_index"""
for index in val_index:
    print(val_index)
    break

[0 0 0 0]


* Get the average of the whole matrix

In [80]:
np.mean(N) #getting the mean of the whole 4x4 array

8.5

* Create a vector V with 4 elements, each element is 1

In [86]:
V = np.ones((4), dtype = 'int32') #creating vector named V
V

array([1, 1, 1, 1])

* Take the dot product of N and V

In [87]:
np.dot(N,V) #gettin the dot product of N and V using numpy library

array([10, 26, 42, 58])